/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    locations: Location;
    activities: Activity;
    journal: Journal;
    reservations: Reservation;
    'email-jobs': EmailJob;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    journal: JournalSelect<false> | JournalSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    'email-jobs': EmailJobsSelect<false> | EmailJobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh-CN' | 'en') | ('zh-CN' | 'en')[];
  globals: {
    'portal-home': PortalHome;
    settings: Setting;
  };
  globalsSelect: {
    'portal-home': PortalHomeSelect<false> | PortalHomeSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'zh-CN' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'staff';
  /**
   * Staff can only read/edit activities, reservations, and journal entries for this academy. Ignored for admin role. One-to-one — for multi-academy access, promote to "Admin".
   */
  staffLocation?: (number | null) | Location;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * URL-safe identifier: bangkok / chiangmai / phuket
   */
  slug: string;
  name: string;
  city: string;
  /**
   * Enable only for Thailand-network academies. Standalone pages stay accessible but are excluded from the Thailand portal, switcher, and network feeds.
   */
  isThailandNetwork: boolean;
  tagline?: string | null;
  heroImage: number | Media;
  /**
   * 可选。上传后，该学堂页面顶栏将显示此 logo；未上传时显示学堂名称。建议横版、透明背景 PNG，高度 ≥ 200px。
   */
  logo?: (number | null) | Media;
  /**
   * Academy story (replaces About global)
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. The small tagline shown below the story, e.g. "We sit, drink tea, read, copy sutras." Leave blank to fall back to the default ("We sit, drink tea, read, and walk together.").
   */
  signatureLine?: string | null;
  address?: string | null;
  /**
   * Google Maps embed URL
   */
  mapEmbedUrl?: string | null;
  /**
   * How to get here
   */
  transport?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  team?:
    | {
        name: string;
        photo?: (number | null) | Media;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Academy contact email
   */
  email?: string | null;
  phone?: string | null;
  /**
   * 微信号 / WeChat ID (text handle, e.g. xindeng_cm)
   */
  wechatId?: string | null;
  /**
   * WhatsApp number with country code (e.g. +66 81 234 5678) or a wa.me/... URL
   */
  whatsapp?: string | null;
  /**
   * WeChat QR code image
   */
  wechatQr?: (number | null) | Media;
  social?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        q: string;
        a: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Sort order on the portal home page (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * AI-generated after upload for accessibility and search. You can edit it; manual text is never overwritten.
   */
  alt?: string | null;
  /**
   * Internal: used by seed scripts for idempotent lookups. Not displayed.
   */
  seedKey?: string | null;
  /**
   * Mark Unsplash/stock placeholders to review before launch
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-safe identifier; auto-generated from name if left blank
   */
  slug: string;
  /**
   * Sort order in category lists (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  /**
   * Used in the page URL. **Leave blank to auto-generate from the Chinese title via AI translation** (academy names stay in pinyin: Ruru / Xindeng / Heguang); or enter English manually (lowercase letters, numbers, hyphens). Must be unique.
   */
  slug: string;
  category: number | Category;
  location: number | Location;
  heroImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Short description shown in list views (max 240 characters)
   */
  shortDesc: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  venueNote?: string | null;
  capacity: number;
  /**
   * Internal notes (visible to admin/staff only in context)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Add occurrences manually using "+ Add Row". Weekly/multi-day quick-add coming in v1.1.
   */
  occurrences?:
    | {
        startAt: string;
        endAt: string;
        /**
         * Leave blank to use the activity-level capacity
         */
        capacityOverride?: number | null;
        status: 'open' | 'full' | 'cancelled' | 'deleted';
        internalNotes?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal".
 */
export interface Journal {
  id: number;
  title: string;
  /**
   * Used in the page URL. **Leave blank to auto-generate from the Chinese title via AI translation** (academy names stay in pinyin: Ruru / Xindeng / Heguang); or enter English manually (lowercase letters, numbers, hyphens). Must be unique.
   */
  slug: string;
  date: string;
  location: number | Location;
  /**
   * Optional. Only activities at the same location are selectable.
   */
  relatedActivity?: (number | null) | Activity;
  coverImage: number | Media;
  /**
   * Generated from the cover image and article context after save. Manual text is never overwritten.
   */
  coverAlt?: string | null;
  photos: {
    image: number | Media;
    caption?: string | null;
    /**
     * Generated after the article is saved; edit it whenever needed.
     */
    alt?: string | null;
    id?: string | null;
  }[];
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  source: 'home_cta' | 'nav_book' | 'book_list' | 'book_general_inquiry' | 'activity_detail' | 'shared_link';
  location: number | Location;
  activity?: (number | null) | Activity;
  /**
   * The occurrence.id within the activity this reservation is for
   */
  occurrenceId?: string | null;
  /**
   * 自动从场次 ID 解析,显示 BKK 本地时间
   */
  occurrenceLabel?: string | null;
  name: string;
  email?: string | null;
  wechatId?: string | null;
  phone: string;
  guests: number;
  /**
   * Interest direction for general inquiries
   */
  direction?: ('meditation' | 'mindfulness' | 'one_on_one' | 'visit' | 'other') | null;
  /**
   * Notes the visitor filled in when submitting the reservation.
   */
  notes?: string | null;
  /**
   * Staff-only. Use for call notes, follow-ups, and any context that should not be visible to the visitor.
   */
  internalNotes?: string | null;
  language: 'zh' | 'en';
  status: 'pending' | 'confirmed' | 'waitlist' | 'cancelled' | 'deleted';
  emailStatus?: ('pending' | 'sent' | 'failed' | 'no_email') | null;
  confirmedAt?: string | null;
  confirmedBy?: (number | null) | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  reminderSentAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-jobs".
 */
export interface EmailJob {
  id: number;
  to: string;
  subject: string;
  body: string;
  /**
   * Sender display name (defaults to 静心学堂 · 泰国). Per-academy emails set this to the academy name.
   */
  fromName?: string | null;
  /**
   * Reply-To header — usually the academy-specific email so replies route correctly.
   */
  replyTo?: string | null;
  /**
   * Pass-through to nodemailer attachments array
   */
  attachments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  relatedReservation?: (number | null) | Reservation;
  attempts?: number | null;
  lastError?: string | null;
  status?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'journal';
        value: number | Journal;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'email-jobs';
        value: number | EmailJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  staffLocation?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  seedKey?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  city?: T;
  isThailandNetwork?: T;
  tagline?: T;
  heroImage?: T;
  logo?: T;
  story?: T;
  signatureLine?: T;
  address?: T;
  mapEmbedUrl?: T;
  transport?: T;
  team?:
    | T
    | {
        name?: T;
        photo?: T;
        bio?: T;
        id?: T;
      };
  email?: T;
  phone?: T;
  wechatId?: T;
  whatsapp?: T;
  wechatQr?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  location?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDesc?: T;
  description?: T;
  venueNote?: T;
  capacity?: T;
  notes?: T;
  occurrences?:
    | T
    | {
        startAt?: T;
        endAt?: T;
        capacityOverride?: T;
        status?: T;
        internalNotes?: T;
        id?: T;
      };
  status?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal_select".
 */
export interface JournalSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  location?: T;
  relatedActivity?: T;
  coverImage?: T;
  coverAlt?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        alt?: T;
        id?: T;
      };
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  source?: T;
  location?: T;
  activity?: T;
  occurrenceId?: T;
  occurrenceLabel?: T;
  name?: T;
  email?: T;
  wechatId?: T;
  phone?: T;
  guests?: T;
  direction?: T;
  notes?: T;
  internalNotes?: T;
  language?: T;
  status?: T;
  emailStatus?: T;
  confirmedAt?: T;
  confirmedBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  reminderSentAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-jobs_select".
 */
export interface EmailJobsSelect<T extends boolean = true> {
  to?: T;
  subject?: T;
  body?: T;
  fromName?: T;
  replyTo?: T;
  attachments?: T;
  relatedReservation?: T;
  attempts?: T;
  lastError?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-home".
 */
export interface PortalHome {
  id: number;
  heroImage: number | Media;
  heroTitle: string;
  heroSubtitle?: string | null;
  ctaPrimary?: {
    label?: string | null;
    href?: string | null;
  };
  ctaSecondary?: {
    label?: string | null;
    href?: string | null;
  };
  middleParagraph?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName: string;
  ogDefault?: (number | null) | Media;
  footerText?: string | null;
  /**
   * 新预约提醒邮箱 / Admin email for new reservation notifications
   */
  adminEmail: string;
  mindfulpeaceOrgUrl?: string | null;
  /**
   * Fallback academy when URL has no location slug (optional)
   */
  defaultLocation?: (number | null) | Location;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-home_select".
 */
export interface PortalHomeSelect<T extends boolean = true> {
  heroImage?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  ctaPrimary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  ctaSecondary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  middleParagraph?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  ogDefault?: T;
  footerText?: T;
  adminEmail?: T;
  mindfulpeaceOrgUrl?: T;
  defaultLocation?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}